name: otomotiv_ariza_tespit
description: AI destekli araç arıza tespit uygulaması

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  audioplayers: ^6.1.0

  # State Management
  provider: ^6.1.1

  # AI
  http: ^1.1.0

  # Audio (temporarily disabled for build)
  # record: ^5.0.4
  permission_handler: ^11.1.0
  path_provider: ^2.1.1

  # Bluetooth OBD
  flutter_bluetooth_serial: ^0.4.0

  # Navigation
  go_router: ^13.0.0
  shared_preferences: ^2.5.4
  share_plus: ^12.0.1
  flutter_blue_plus: 1.35.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/ses/
